app:
  invoice:
    directory: ./invoices  # Diretório onde os PDFs serão salvos

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faturarapida
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.faturarapida: DEBUG
